title: Morethanspaces
email: ns@morethanspaces.custom
description: Tradeshow booth and videowall rental solutions
baseurl: "/morethanspaces" # the subpath of your site, e.g. /blog
url: "http://morethanspaces.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - webpack

prose:
    rooturl: 'assets/discounts/discount.js'
    metadata:
        assets/discounts/discount.js:
        - name: 'amount'
          field:
            element: 'number'
            label: "Specify an amount (Please don't use any signs)"
            value: ''
        - name: 'type'
          field:
            element: 'select'
            label: 'Percentage or Amount'
            placeholder: 'Choose a category'
            options:
              - name: 'Percentage'
                value: 'percentage'
              - name: 'Amount'
                value: 'amount'
        - name: 'text'
          field:
            element: 'text'
            label: 'Discount Text'
            value: ''
