---
title: More Than Spaces | Trade Show & Video Wall Experts – Rent or Own
timezone: UTC
collections:
  conventions:
    title: Conventions
    output: true
    permalink: "/conventions/:title/"
    layout: convention
  discounts:
    title: Discounts
    output: false
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
    permalink: "/:title/"
  uploads:
    title: Uploads
    output: true
  videowalls:
    title: Videowalls
    output: false
defaults:
- scope:
    path: ''
    type: services
  values:
    layout: convention
    title: 
    meta_description: 
    image: 
- scope:
    path: ''
    type: conventions
  values:
    layout: convention
    title: 
    logo: 
    convention_date: 
- scope:
    path: ''
    type: videowalls
  values:
    id: 
    tags:
    - LCD
    - LED
    - Tv
    description: 
    rent: 
    size: 
    diagonal: 
    featured: true
    images:
      url: 
email: hello@morethanspaces.com
description: Get more for less! See exclusive trade show booth designs in 3D & VR.
  Rent/Own. Video walls rental. Vegas & Nationwide. World Class Friendly Service.
og_image: "/assets/img/og_image.png"
baseurl: 
url: http://morethanspaces.com
markdown: kramdown
gems:
- jekyll-feed
- octopress-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- webpack
sass:
  style: compressed
github:
- metadata
