title: More than spaces
email: ns@morethanspaces.custom
description: Tradeshow booth and videowall rental solutions
baseurl: "/morethanspaces" # the subpath of your site, e.g. /blog
url: "http://morethanspaces.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - webpack

collections:
  conventions:
    output: true
    permalink: /conventions/:path/

prose:
    rooturl: 'assets/discounts'
    media: 'assets/img/conventions'
    metadata:
        assets/discounts:
        - name: 'amount'
          field:
            element: 'number'
            label: "Specify an amount (Please don't use any signs)"
            value: ''
        - name: 'type'
          field:
            element: 'select'
            label: 'Percentage or Amount'
            placeholder: 'Choose a category'
            options:
              - name: 'Percentage'
                value: 'percentage'
              - name: 'Amount'
                value: 'amount'
        - name: 'text'
          field:
            element: 'text'
            label: 'Discount text'
            value: ''
        - name: 'smalltext'
          field:
            element: 'text'
            label: 'Discount small text'
            value: ''
