---
title: More Than Spaces | Trade Show & Video Wall Experts – Rent or Own
timezone: UTC
collections:
  conventions:
    title: Conventions
    output: true
    permalink: "/conventions/:title/"
  discounts:
    title: Discounts
    output: true
    permalink: "/d/s/:title/"
  posts:
    title: Videowalls
    output: true
  services:
    title: Services
    output: true
    permalink: "/:title/"
  uploads:
    title: Uploads
    output: true
email: hello@morethanspaces.com
description: Get more for less! See exclusive trade show booth designs in 3D & VR.
  Rent/Own. Video walls rental. Vegas & Nationwide. World Class Friendly Service.
og_image: "/assets/img/og_image.png"
baseurl: 
url: http://morethanspaces.com
markdown: kramdown
gems:
- jekyll-feed
- octopress-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- webpack
sass:
  style: compressed
github:
- metadata
<<<<<<< HEAD

defaults:
  -
    scope:
      path: ""
      type: "services"
    values:
      layout: "convention"
      title:
      meta_description:
      image: 
  -
    scope:
      path: ""
      type: "conventions"
    values:
      layout: "convention"
      title: 
      logo: 
      convention_date: 
=======
>>>>>>> 5dae6025d872bd859dfef0e7031078a3a311dc13
